### PR TITLE
Implementation of CreateCard method

### PR DESCRIPTION
**Pull request by adixon**
Implementation of CreateCard method, with some side-effect cleanups.

Side-effect cleanups should be mostly self-explanatory. The refactoring of the tamper proof seal was needed due to the use of the card on file option. I also figured it was better to implement it as something that gets added immediately before sending it out (because as it was, some of the data values could change after the tps was created).

### CODE REVIEW

**Comment by zburke** [comment]
Can you clean up the formatting so the Travis builds pass? I'll try to take a look at this functionality and merge soon.

**Comment by adixon** [comment]
Ah - it's because I've got my vim set for drupal formatting and was just manually trying to make it match ... is there a name or vim plugin for the format that you need?

**Comment by zburke** [comment]
It's PSR2. If you have phpcs installed (https://github.com/squizlabs/PHP_CodeSniffer) you should be able to get a report with a command like `phpcs --standard=PSR2 src`.

**Comment by yojance** [comment]
Hello @zburke 

Is this ready to be merged into Master? I would like to use this feature, too.

Thanks.

**Pull request merged**
